In [6]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import torchvision.transforms as transforms


# Set up parameters for diffusion
timesteps = 10  # Number of diffusion steps
beta_start = .0001  # Small amount of initial noise
beta_end = .2   # Final amount of noise



In [9]:
# Create a linear schedule for beta values (variance of noise added at each step)
betas = torch.linspace(beta_start, beta_end, timesteps)
print(betas)
print(betas.shape)
# Calculate alpha values based on betas
alphas = 1.0 - betas
print(alphas)
print(alphas.shape)
alphas_cumprod = torch.cumprod(alphas, dim=0)
print(alphas_cumprod)
print(alphas_cumprod.shape)




tensor([1.0000e-04, 2.2311e-02, 4.4522e-02, 6.6733e-02, 8.8944e-02, 1.1116e-01,
        1.3337e-01, 1.5558e-01, 1.7779e-01, 2.0000e-01])
torch.Size([10])
tensor([0.9999, 0.9777, 0.9555, 0.9333, 0.9111, 0.8888, 0.8666, 0.8444, 0.8222,
        0.8000])
torch.Size([10])
tensor([0.9999, 0.9776, 0.9341, 0.8717, 0.7942, 0.7059, 0.6118, 0.5166, 0.4247,
        0.3398])
torch.Size([10])


In [63]:
y = torch.sqrt(alphas_cumprod[0]).view(-1,1,1,1)
print(y)
print(y.shape)

y1 = torch.sqrt(1 - alphas_cumprod[0]).view(-1,1,1,1)
print(y1)
print(y1.shape)

tensor([[[[0.9999]]]])
torch.Size([1, 1, 1, 1])
tensor([[[[0.0100]]]])
torch.Size([1, 1, 1, 1])


In [73]:
torch.manual_seed(42)
img = torch.round(torch.rand(2, 3, 4, 4), decimals=2)
print(img)
print(img.shape)

noise = torch.round(torch.randn(img.shape), decimals=2)
print(noise)
print(noise.shape)

tensor([[[[0.8800, 0.9200, 0.3800, 0.9600],
          [0.3900, 0.6000, 0.2600, 0.7900],
          [0.9400, 0.1300, 0.9300, 0.5900],
          [0.8700, 0.5700, 0.7400, 0.4300]],

         [[0.8900, 0.5700, 0.2700, 0.6300],
          [0.2700, 0.4400, 0.3000, 0.8300],
          [0.1100, 0.2700, 0.3600, 0.2000],
          [0.5500, 0.0100, 0.9500, 0.0800]],

         [[0.8900, 0.5800, 0.3400, 0.8100],
          [0.5800, 0.9000, 0.5500, 0.3400],
          [0.6300, 0.3600, 0.7100, 0.9500],
          [0.7900, 0.2800, 0.7900, 0.5900]]],


        [[[0.7500, 0.2000, 0.0100, 0.3100],
          [0.1200, 0.9100, 0.6400, 0.7100],
          [0.6600, 0.4900, 0.8900, 0.1400],
          [0.5300, 0.1600, 0.6500, 0.3300]],

         [[0.6500, 0.4000, 0.9100, 0.2000],
          [0.2000, 0.2000, 0.9500, 0.6700],
          [0.9800, 0.0900, 0.0000, 0.1100],
          [0.1600, 0.7000, 0.6800, 0.9200]],

         [[0.2400, 0.1600, 0.7700, 0.3000],
          [0.8000, 0.3800, 0.7900, 0.1100],
          [0.2500, 0

In [65]:
img

tensor([[[[0.8800, 0.9200, 0.3800, 0.9600],
          [0.3900, 0.6000, 0.2600, 0.7900],
          [0.9400, 0.1300, 0.9300, 0.5900],
          [0.8700, 0.5700, 0.7400, 0.4300]],

         [[0.8900, 0.5700, 0.2700, 0.6300],
          [0.2700, 0.4400, 0.3000, 0.8300],
          [0.1100, 0.2700, 0.3600, 0.2000],
          [0.5500, 0.0100, 0.9500, 0.0800]],

         [[0.8900, 0.5800, 0.3400, 0.8100],
          [0.5800, 0.9000, 0.5500, 0.3400],
          [0.6300, 0.3600, 0.7100, 0.9500],
          [0.7900, 0.2800, 0.7900, 0.5900]]]])

In [76]:
t = torch.tensor([0.1, .5]).view(-1,1,1,1)
print(t)
print(t.shape)
print(img.shape)
t * img

tensor([[[[0.1000]]],


        [[[0.5000]]]])
torch.Size([2, 1, 1, 1])
torch.Size([2, 3, 4, 4])


tensor([[[[0.0880, 0.0920, 0.0380, 0.0960],
          [0.0390, 0.0600, 0.0260, 0.0790],
          [0.0940, 0.0130, 0.0930, 0.0590],
          [0.0870, 0.0570, 0.0740, 0.0430]],

         [[0.0890, 0.0570, 0.0270, 0.0630],
          [0.0270, 0.0440, 0.0300, 0.0830],
          [0.0110, 0.0270, 0.0360, 0.0200],
          [0.0550, 0.0010, 0.0950, 0.0080]],

         [[0.0890, 0.0580, 0.0340, 0.0810],
          [0.0580, 0.0900, 0.0550, 0.0340],
          [0.0630, 0.0360, 0.0710, 0.0950],
          [0.0790, 0.0280, 0.0790, 0.0590]]],


        [[[0.3750, 0.1000, 0.0050, 0.1550],
          [0.0600, 0.4550, 0.3200, 0.3550],
          [0.3300, 0.2450, 0.4450, 0.0700],
          [0.2650, 0.0800, 0.3250, 0.1650]],

         [[0.3250, 0.2000, 0.4550, 0.1000],
          [0.1000, 0.1000, 0.4750, 0.3350],
          [0.4900, 0.0450, 0.0000, 0.0550],
          [0.0800, 0.3500, 0.3400, 0.4600]],

         [[0.1200, 0.0800, 0.3850, 0.1500],
          [0.4000, 0.1900, 0.3950, 0.0550],
          [0.1250, 0

In [ ]:
# Function for sampling Gaussian noise
def sample_gaussian_noise(shape):
    return torch.randn(shape)

# Forward diffusion sampling function
def forward_diffusion_sample(x_0, t):
    """
    Add noise to the input image x_0 at time step t.
    
    Parameters:
        x_0: Original image (batch of images)
        t: Time step (0 <= t < timesteps)
        
    Returns:
        Noisy image x_t
    """
     # Calculate scaling factors for original image and noise
    sqrt_alpha_cumprod_t = torch.sqrt(alphas_cumprod[t]).view(-1, 1, 1, 1)
    sqrt_one_minus_alpha_cumprod_t = torch.sqrt(1 - alphas_cumprod[t]).view(-1, 1, 1, 1)
    noise = sample_gaussian_noise(x_0.shape)

    # Generate noisy image
    x_t = sqrt_alpha_cumprod_t * x_0 + sqrt_one_minus_alpha_cumprod_t * noise
    return x_t, noise

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F


def sinusoidal_embedding(timesteps, embedding_dim, theta=10000.0):
    """
    Generate sinusoidal embeddings for the given timesteps.

    Args:
        timesteps (torch.Tensor): A tensor of shape (batch_size,) containing integer timestep values.
        embedding_dim (int): The dimension of the embedding.

    Returns:
        torch.Tensor: A tensor of shape (batch_size, embedding_dim) containing the sinusoidal embeddings.
    """
    embed_idx = torch.arange(0, embedding_dim // 2, dtype=torch.float32)
    base = theta ** (2 * embed_idx / embedding_dim)

    input = timesteps / base

    embeddings = torch.cat([torch.sin(input), torch.cos(input)], dim=1)

    return embeddings

class ConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1):
        super(ConvBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
        self.gn1 = nn.GroupNorm(2, out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size, stride, padding)
        self.gn2 = nn.GroupNorm(2, out_channels)

    def forward(self, x):
        out = F.gelu(self.gn1(self.conv1(x)))
        out = F.gelu(self.gn2(self.conv2(out)))
        return out

class DownSampleBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, embedding_dim=32, pool=False):
        super(DownSampleBlock, self).__init__()
        self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.convblk1 = ConvBlock(in_channels, out_channels, kernel_size, stride, padding)
        self.convblk2 = ConvBlock(out_channels, out_channels, kernel_size, stride, padding)
        self.tsembed  = nn.Linear(embedding_dim, out_channels)
        self.pool = pool

    def forward(self, x, t=None):
        if self.pool:
            x = self.maxpool(x)
        out = self.convblk1(x)
        out = self.convblk2(out)
        
        # add timestep embedding
        if t is None:
            tsembed = F.silu(self.tsembed(t))
            tsembed = tsembed[:, :, None, None]
            out += tsembed
        return out
    
    
class UpSampleBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=2, stride=2):
        super(UpSampleBlock, self).__init__()
        self.conv1 = nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride)
        self.gn1 = nn.GroupNorm(2, out_channels)

    def forward(self, x):
        out = F.gelu(self.gn1(self.conv1(x)))
        return out
    
class DiffModel(nn.Module):
    def __init__(self, in_channels=3, out_channels=3, embedding_dim=64):
        super(DiffModel, self).__init__()
        
        self.enc1 = DownSampleBlock(in_channels, 64)
        self.enc2 = DownSampleBlock(64, 128, pool=True)
        self.enc3 = DownSampleBlock(128, 256, pool=True)
        self.enc4 = DownSampleBlock(256, 512, pool=True)
        
        self.bottleneck = DownSampleBlock(512, 1024, pool=True)
        
        self.upconv4 = UpSampleBlock(1024, 512)
        self.dec4 = ConvBlock(1024, 512)
        
        self.upconv3 = UpSampleBlock(512, 256)
        self.dec3 = ConvBlock(512, 256)
        
        self.upconv2 = UpSampleBlock(256, 128)
        self.dec2 = ConvBlock(256, 128)
        
        self.upconv1 = UpSampleBlock(128, 64)
        self.dec1 = ConvBlock(128, 64)
        
        self.final_layer = nn.Conv2d(64, out_channels, kernel_size=1)
        
        
    def forward(self, x, t=None):
        e1 = self.enc1(x, t)
        e2 = self.enc2(e1, t)
        e3 = self.enc3(e2, t)
        e4 = self.enc4(e3, t)

        bottleneck = self.bottleneck(e4, t)
               
        up4 = self.upconv4(bottleneck)
        up4 = torch.cat((e4, up4), dim=1)
        d4 = self.dec4(up4)
        
        up3 = self.upconv3(d4)
        up3 = torch.cat((e3, up3), dim=1)
        d3 = self.dec3(up3)
        
        up2 = self.upconv2(d3)
        up2 = torch.cat((e2, up2), dim=1)
        d2 = self.dec2(up2)
        
        up1 = self.upconv1(d2)
        up1 = torch.cat((e1, up1), dim=1)
        d1 = self.dec1(up1)

        return self.final_layer(d1)
    
moodel = DiffModel()
img = torch.rand(2, 3, 32, 32)
y = moodel(img, torch.Tensor([0.1, .5]))
print(y.shape)

torch.Size([2, 3, 32, 32])


In [5]:
img = torch.rand(2, 3, 32, 32)
conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1)
gn1 = nn.GroupNorm(2, 16)
x1 = conv1(img)
print(x1.shape)
x2 = F.gelu(gn1(x1))
print(x2.shape)

torch.Size([2, 16, 32, 32])
torch.Size([2, 16, 32, 32])
